package com.example.takwafortress.util.constants

/**
 * Central registry of package names the fortress knows about.
 *
 * BROWSERS      – suspended (greyed out, still visible in app drawer)
 * NUCLEAR_BLACKLIST – hidden completely (invisible in launcher)
 */
object BlockedPackages {

    /** packageName → friendly display name */
    val BROWSERS: Map<String, String> = mapOf(
        "com.opera.browser"                     to "Opera Browser",
        "com.opera.browser.preinstall"          to "Opera Browser (Pre-installed)",
        "org.mozilla.firefox"                   to "Firefox",
        "com.microsoft.teams"                   to "Microsoft Edge",
        "com.microsoft.launcher"                to "Microsoft Edge (Launcher)",
        "com.duckduckgo.android.core"           to "DuckDuckGo Browser",
        "com.brave.browser"                     to "Brave Browser",
        "com.google.android.apps.chrome"        to "Chrome (duplicate check)",
        "com.sec.android.app.samsunginternet"   to "Samsung Internet"
    )

    /** packageName → friendly display name */
    val NUCLEAR_BLACKLIST: Map<String, String> = mapOf(
        "org.telegram.messenger"                to "Telegram",
        "com.reddit.client"                     to "Reddit",
        "com.twitter.android"                   to "X (Twitter)",
        "com.discord"                           to "Discord",

        // ── Added from all_apps_and_sites.docx ──────────────────────────
        "org.thunderdog.challegram"               to "Telegram X",
        "proxy.browser.unblock.sites.proxybrowser.unblocksites" to "proxy.browser.unblock.sites.proxybrowser.unblocksites",
        "org.plus18.android"                      to "org.plus18.android",
        "chat.revolt"                             to "Stoat",
        "com.reddit.frontpage"                    to "Reddit",
        "xyz.blueskyweb.app"                      to "Bluesky",
        "org.joinmastodon.android"                to "Mastodon",
        "videoplayer.videodownloader.downloader"  to "videoplayer.videodownloader.downloader",
        "com.neurobro.browser"                    to "Neuro Browser",
        "com.vivaldi.browser"                     to "com.vivaldi.browser",
        "com.dajiu.stay"                          to "com.dajiu.stay",
        "net.quetta.browser"                      to "net.quetta.browser",
        "com.ycngmn.weblo"                        to "Weblo",
        "com.libertyvaults.wiko"                  to "com.libertyvaults.wiko",
        "com.startpage.app"                       to "com.startpage.app",
        "company.thebrowser.arc"                  to "company.thebrowser.arc",
        "com.brave.browser_nightly"               to "com.brave.browser_nightly",
        "io.friendly"                             to "Friendly",
        "com.deep.search.browser"                 to "com.deep.search.browser",
        "com.chimbori.hermitcrab"                 to "com.chimbori.hermitcrab",
        "com.google.ar.core"                      to "Google Play Services for AR",
        "io.friendly.twitter"                     to "Friendly For Twitter",
        "org.torproject.torbrowser"               to "org.torproject.torbrowser",
        "net.onecook.browser"                     to "net.onecook.browser",
        "com.medium.reader"                       to "Medium",
        "com.hootsuite.droid.full"                to "Hootsuite",
        "org.buffer.android"                      to "Buffer",
        "com.fedica.android"                      to "Fedica",
        "com.allsocialmediaapp.fastechpointapp"   to "All social Media In One App",
        "browser.vego.me"                         to "browser.vego.me",
        "com.all.one.social.media.network"        to "All Apps",
        "com.a_studio.socialmediapro"             to "All In One",
        "socialallinoneapp.allsocialmediaapps"    to "All Messenger",
        "com.socialmedia.allsocial"               to "All Social",
        "tutorials.seoschemes.sonyaath"           to "All Social Media -- All in One Social Media App",
        "messenger.video.call.chat.free"          to "All in 1 Video Messenger",
        "com.social.hemapp"                       to "All in One Social App",
        "social.app.india2010"                    to "All in One Social App",
        "com.technopath.myapplication"            to "All in one",
        "socialpilot.co"                          to "SocialPilot",
        "com.rainbow.aiobrowser"                  to "Smart App",
        "my.socialmedia"                          to "Social Media",
        "com.ronstech.allsocialmediaapp"          to "Social Networking Apps",
        "com.sclbrd.app"                          to "SocialBoard",
        "com.all_social_media.social_media"       to "Social Media",
        "dev.liukkonen.socialwrap"                to "SocialWrap",
        "com.socialbu.app"                        to "Socialbu",
        "io.publer"                               to "Publer",
        "com.vistasocial.android"                 to "VistaSocial",
        "com.sec.android.app.samsungapps"         to "Galaxy Store",
        "the.best.gram"                           to "Bestgram",
        "com.sociallite.android"                  to "SocialLite",
        "org.vidogram.lite"                       to "Vidogram Lite",
        "com.pl.premierleague"                    to "com.pl.premierleague",
        "com.facebook.katana"                     to "Facebook",
        "jp.ejimax.berrybrowser"                  to "jp.ejimax.berrybrowser",
        "com.ask.browser.ai"                      to "com.ask.browser.ai",
        "com.panalinks.webkey"                    to "Webview Open Site",
        "com.nktnet.webview_kiosk"                to "com.nktnet.webview_kiosk",
        "com.tcl.browser"                         to "com.tcl.browser",
        "de.ozerov.fully"                         to "de.ozerov.fully",
        "com.transsion.phoenix"                   to "com.transsion.phoenix",
        "com.snc.test.webview2"                   to "WEBVIEW TEST",
        "com.webview.space"                       to "WebView App",
        "com.tph.webViewappbuilder"               to "WebView App Builder",
        "com.brouken.websearch"                   to "Web Search Customizer",
        "com.webtoapp.converter"                  to "Web to App",
        "com.webviewstudio.app"                   to "WebView Studio",
        "com.webtoapp.convertwebsitetoapp"        to "WebtoApp",
        "com.xckevin.android.app.webview.test"    to "WebViewTest",
        "com.atriidev.webtoappconverter"          to "WebInto.App",
        "com.nexech.webview.basic"                to "WebView Basic",
        "com.nexech.webview.premium"              to "WebView Premium",
        "com.appbin.webviewworld"                 to "WebView World",
        "com.nexech.webview.standard"             to "WebView Standard",
        "com.AcmuStudio.webviewtest"              to "WebView Test",
        "com.webtoapp.converter.appmaker"         to "Website to App Builder",
        "com.webviewtest.app"                     to "WebView Test",
        "com.azc.terminet"                        to "TermiNet",
        "com.sec.android.app.wlantest"            to "WlanTest",
        "mgks.os.swv"                             to "Smart WebView",
        "com.chrome.dev"                          to "com.chrome.dev",
        "com.brgwebview.sa"                       to "BRG Webview",
        "com.satisfilabs.webclient"               to "Satisfi Webview Tester",
        "com.studentpasscard.driverappw"          to "Passcard Driver App WebView",
        "com.ncnp.app"                            to "Natively",
        "com.webviewnova.app"                     to "Split Browser: Remote Kiosk",
        "com.samsung.android.inputshare"          to "Multi control",
        "ua.tiar.devsurf"                         to "ua.tiar.devsurf",
        "com.probuse.odoo"                        to "Mobile WebView for Odoo",
        "com.sec.epdgtestapp"                     to "EpdgTestApp",
        "ooo.alienz.devinspector"                 to "Devel Browser",
        "com.freekiosk"                           to "FreeKiosk",
        "com.rikpro.free"                         to "com.rikpro.free",
        "com.freewebtoapk"                        to "AppMint",
        "com.talpa.hibrowser"                     to "com.talpa.hibrowser",
        "com.phlox.tvwebbrowser"                  to "com.phlox.tvwebbrowser",
        "com.nexaford.webstore"                   to "Webify",
        "com.webviewcli"                          to "Webviewcli",
        "com.jcd.webvisiona28"                    to "WEBVISION A",
        "com.app.dr1009.webviewchecker"           to "webview_checker",
        "com.multipower.multiwebview"             to "multipower",
        "com.letsgoup.uServeWebview"              to "uServe",
        "com.exocad.webview"                      to "exocad webview",
        "com.google.android.apps.searchlite"      to "Google Go",
        "com.craftonative.webtoapp.converter.appbuilder.websitetoapp" to "Craft 2 Native",
        "com.ssolstice.browser"                   to "com.ssolstice.browser",
        "de.mxapplications.kmp.app.webdevstudio"  to "Webli",
        "com.lozsolutiont.htmlviewer"             to "HTML Viewer",
        "com.explore.web.browser"                 to "com.explore.web.browser",
        "reactivephone.msearch"                   to "reactivephone.msearch",
        "com.instantbits.cast.webvideo"           to "com.instantbits.cast.webvideo",
        "com.opera.gx"                            to "com.opera.gx",
        "com.fly.web.smart.browser"               to "com.fly.web.smart.browser",
        "com.qwant.liberty"                       to "com.qwant.liberty",
        "com.cloudmosa.puffinFree"                to "com.cloudmosa.puffinFree",
        "com.kagi.search"                         to "Kagi Search",
        "com.goodtoolapps.zeus"                   to "com.goodtoolapps.zeus",
        "org.mozilla.fenix"                       to "org.mozilla.fenix",
        "com.aospstudio.quicksearch"              to "com.aospstudio.quicksearch",
        "com.ecosia.android"                      to "com.ecosia.android",
        "com.kagi.smallweb"                       to "Small Web",
        "com.devhomc.search"                      to "SearchBar Ex",
        "rk.android.app.pixelsearch"              to "Pixel Search",
        "com.zerch.widget"                        to "Zerch",
        "com.yep.search"                          to "Yep",
        "com.chrome.canary"                       to "com.chrome.canary",
        "org.mozilla.firefox_beta"                to "org.mozilla.firefox_beta",
        "org.mozilla.focus"                       to "org.mozilla.focus",
        "com.duckduckgo.mobile.android"           to "com.duckduckgo.mobile.android",
        "com.fooview.android.fooview"             to "com.fooview.android.fooview",
        "shareit.lite"                            to "shareit.lite",
        "com.quora.android"                       to "Quora",
    )

    /**
     * Returns a friendly name for any known package, or the raw package name as fallback.
     */
    fun getFriendlyName(packageName: String): String {
        return BROWSERS[packageName]
            ?: NUCLEAR_BLACKLIST[packageName]
            ?: packageName
    }

    /**
     * All known packages (browsers + nuclear) in one set – handy for quick lookup.
     */
    val ALL_BLOCKED: Set<String> = BROWSERS.keys + NUCLEAR_BLACKLIST.keys
}